### ISSUE TITLE
Test case randomly fails

### ISSUE THREAD

**Issue by Grandpa-G** [SequentMicrosystems/4relind-rpi#4]
Using the test.py, I get random errors:

set relay 1 ON
set relay 2 ON
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 79, in __ident
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 62, in __check
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 83, in __ident
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 62, in __check
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 87, in __ident
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 62, in __check
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/hyperbaric/hat.py", line 6, in <module>
    r.set_relay(0, i+1, 1)
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 98, in set_relay
  File "/usr/local/lib/python3.9/dist-packages/lib4relind-1.0.3-py3.9.egg/lib4relind/__init__.py", line 90, in __ident
RuntimeError: Unable to communicate with 4relind with exception [Errno 5] Input/output error

**Comment by alexburcea2877** [comment]
Hi,
This can be happening because poor contact on the 40 pins connector, please use provided standoffs. One different cause might be the raspberry I2C port or driver witch can not handle so many requests, and for that you need to edit the example and add some delays  (time.sleep(0.1) ) between card access calls.
